app = 'ev-stage'
primary_region = 'sea'
console_command = '/code/manage.py shell'

[env]
  CSRF = "https://*.fly.dev"
  ENVIRONMENT = "PLACEHOLDER_ENVIRONMENT"
  ROOT = "PLACEHOLDER_ROOT"
  HOST = "PLACEHOLDER_HOST"
  DB_USER = "PLACEHOLDER_DB_USER"
  DB_PASSWORD = "PLACEHOLDER_DB_PASSWORD"
  DB_HOSTNAME = "PLACEHOLDER_DB_HOSTNAME"
  DB_URL = "PLACEHOLDER_DB_URL"
  STATIC_CDN = "PLACEHOLDER_STATIC_CDN"
  SECRET_KEY = "PLACEHOLDER_SECRET_KEY"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'

[[statics]]
  guest_path = '/code/static'
  url_prefix = '/static/'
