app = 'stage'
primary_region = 'sea'
console_command = '/code/manage.py shell'

[env]
  CSRF = "https://*.fly.dev"
  ENVIRONMENT = "PLACEHOLDER_ENVIRONMENT"
  PORT = "PLACEHOLDER_PORT"
  ROOT = "PLACEHOLDER_ROOT"
  HOST = "PLACEHOLDER_HOST"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'

[[statics]]
  guest_path = '/code/static'
  url_prefix = '/static/'
