name: Deploy main to Fly
on:
  push:
    branches: [main]

env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
  ROOT: ${{ secrets.ROOT }}
  HOST: ${{ secrets.HOST }}
  ENVIRONMENT: ${{ secrets.ENVIRONMENT }}
  APP_NAME: ${{ secrets.APP_NAME }}
  DB_USER: ${{ secrets.DB_USER }}
  DB_NAME: ${{ secrets.DB_NAME }}
  DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
  DB_HOST: ${{ secrets.DB_HOST }}
  STATIC_CDN: ${{ secrets.STATIC_CDN }}
  SECRET_KEY: ${{ secrets.SECRET_KEY }}

jobs:
  deploy:
    name: Deploy to Fly
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Replace secrets in fly.toml
        working-directory: ./src/backend
        run: |
          sed -i "s|PLACEHOLDER_ROOT|${{ env.ROOT }}|g" fly.toml
          sed -i "s|PLACEHOLDER_HOST|${{ env.HOST }}|g" fly.toml
          sed -i "s|PLACEHOLDER_ENVIRONMENT|${{ env.ENVIRONMENT }}|g" fly.toml
          sed -i "s|PLACEHOLDER_DB_NAME|${{ env.DB_NAME }}|g" fly.toml
          sed -i "s|PLACEHOLDER_DB_USER|${{ env.DB_USER }}|g" fly.toml
          sed -i "s|PLACEHOLDER_DB_PASSWORD|${{ env.DB_PASSWORD }}|g" fly.toml
          sed -i "s|PLACEHOLDER_DB_HOST|${{ env.DB_HOST }}|g" fly.toml
          sed -i "s|PLACEHOLDER_STATIC_CDN|${{ env.STATIC_CDN }}|g" fly.toml
          sed -i "s|PLACEHOLDER_SECRET_KEY|${{ env.SECRET_KEY }}|g" fly.toml

      - name: Setup flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Deploy
        run: flyctl deploy --app ${{ env.APP_NAME }}
        working-directory: ./src/backend
