name: Deploy development to Fly
on:
  push:
    branches: [development]

env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
  ROOT: ${{ secrets.STAGE_ROOT }}
  HOST: ${{ secrets.STAGE_HOST }}
  ENVIRONMENT: ${{ secrets.STAGE_ENVIRONMENT }}
  APP_NAME: ${{ secrets.STAGE_APP_NAME }}

jobs:
  deploy:
    name: Deploy to Fly
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Replace secrets in fly.toml
        working-directory: ./src/backend
        run: |
          sed -i "s|PLACEHOLDER_PORT|"$PORT"|g" fly.toml
          sed -i "s|PLACEHOLDER_ROOT|"$ROOT"|g" fly.toml
          sed -i "s|PLACEHOLDER_HOST|"$HOST"|g" fly.toml
          sed -i "s|PLACEHOLDER_ENVIRONMENT|"$ENVIRONMENT"|g" fly.toml

      - name: Setup flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Deploy
        run: flyctl deploy --app $APP_NAME
        working-directory: ./src/backend
