name: Deploy development to Fly
on:
  push:
    branches: [development]

env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
  ROOT: ${{ secrets.STAGE_ROOT }}
  HOST: ${{ secrets.STAGE_HOST }}
  ENVIRONMENT: ${{ secrets.STAGE_ENVIRONMENT }}
  APP_NAME: ${{ secrets.STAGE_APP_NAME }}
  DB_USER: ${{ secrets.STAGE_DB_USER }}
  DB_PASSWORD: ${{ secrets.STAGE_DB_PASSWORD }}
  DB_HOSTNAME: ${{ secrets.STAGE_DB_HOSTNAME }}
  DB_URL: ${{ secrets.STAGE_DB_URL }}
  STATIC_CDN: ${{ secrets.STATIC_CDN }}
  SECRET_KEY: ${{ secrets.SECRET_KEY }}

jobs:
  deploy:
    name: Deploy to Fly
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Replace secrets in fly.toml
        working-directory: ./src/backend
        run: |
          sed -i "s|PLACEHOLDER_ROOT|${{ env.ROOT }}|g" fly.toml
          sed -i "s|PLACEHOLDER_HOST|${{ env.HOST }}|g" fly.toml
          sed -i "s|PLACEHOLDER_ENVIRONMENT|${{ env.ENVIRONMENT }}|g" fly.toml
          sed -i "s|PLACEHOLDER_DB_USER|${{ env.DB_USER }}|g" fly.toml
          sed -i "s|PLACEHOLDER_DB_PASSWORD|${{ env.DB_PASSWORD }}|g" fly.toml
          sed -i "s|PLACEHOLDER_DB_HOSTNAME|${{ env.DB_HOSTNAME }}|g" fly.toml
          sed -i "s|PLACEHOLDER_DB_URL|${{ env.DB_URL }}|g" fly.toml
          sed -i "s|PLACEHOLDER_STATIC_CDN|${{ env.STATIC_CDN }}|g" fly.toml
          sed -i "s|PLACEHOLDER_SECRET_KEY|${{ env.SECRET_KEY }}|g" fly.toml

      - name: Setup flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Deploy
        run: flyctl deploy --app ${{ env.APP_NAME }}
        working-directory: ./src/backend
